import { AnalyzeResponse, HistoryItem } from "@/types";

export const MOCK_RESPONSE: AnalyzeResponse = {
  detected_language: "en",
  output_language: "en",
  supported_languages: [
    { code: "en", name: "English", native_name: "English" },
    { code: "hi", name: "Hindi", native_name: "हिन्दी" },
    { code: "mr", name: "Marathi", native_name: "मराठी" },
    { code: "bn", name: "Bengali", native_name: "বাংলা" },
    { code: "ta", name: "Tamil", native_name: "தமிழ்" },
    { code: "te", name: "Telugu", native_name: "తెలుగు" },
    { code: "kn", name: "Kannada", native_name: "ಕನ್ನಡ" },
    { code: "gu", name: "Gujarati", native_name: "ગુજરાતી" },
    { code: "pa", name: "Punjabi", native_name: "ਪੰਜਾਬੀ" },
  ],
  redactions: ["email", "phone"],
  document_type: "Legal Notice",
  case_type: "Payment / Recovery",
  tone: "threatening/urgent",
  extracted_fields: {
    dates: ["2025-03-15", "2025-04-01"],
    amounts: ["INR 85,000", "INR 1,20,000"],
    reference_numbers: ["LN/2025/MH/04421", "HC-PUNE-2025"],
  },
  notice_details: {
    sender: "M/s RK Recovery Associates, Pune",
    receiver: "The addressee named in the notice",
    subject: "Legal Notice for alleged outstanding dues",
    issue_problem: "The notice alleges unpaid financial dues and threatens further legal action if payment is not made.",
    demanded_action: "Make payment of the claimed amount and respond within the stated period.",
    possible_consequences: ["Further legal action may be initiated.", "The sender claims recovery proceedings may follow if no reply is sent."],
    deadlines: ["Reply within 15 days"],
    authority_sender_type: "Advocate or recovery agent on behalf of a claimant",
    supporting_lines: [
      "Subject: Legal Notice for Recovery of Outstanding Amount",
      "You are hereby called upon to make payment within 15 days of receipt of this notice.",
    ],
  },
  risk_score: 72,
  risk_label: "Suspicious",
  risk_reasons: [
    "Suspicious phrase found: urgent payment",
    "Unofficial email domain detected",
    "Missing official seal or letterhead",
  ],
  deadlines: ["Reply within 15 days"],
  deadline_items: [
    {
      label: "Reply to the notice",
      date: "2025-04-15",
      days_remaining: 10,
      urgency: "warning",
      status: "active",
      source_basis: "Explicit demand line in the notice",
    },
  ],
  next_steps: [
    { title: "Verify the sender", details: "Check whether the advocate or claimant is genuine before making any payment.", timeframe: "Within 24 hours" },
    { title: "Collect proof", details: "Gather invoices, contracts, bank records, and any prior communication related to the claim.", timeframe: "Within 24-48 hours" },
    { title: "Prepare a cautious reply", details: "Draft a reply that requests supporting records and avoids admitting liability.", timeframe: "Before the response deadline" },
  ],
  summary: "This notice appears to demand payment under a disputed financial claim. The language is urgent and the sender should be verified before any payment or admission.",
  explanation: "You have received a legal notice asking for payment and warning of further proceedings. The safest immediate approach is to verify who sent it, collect your records, and prepare a careful reply rather than paying immediately.",
  reply_draft: "To,\nThe Sender / Concerned Party,\n\nDear Sir/Madam,\n\nI acknowledge receipt of your notice. Please provide the supporting documents, calculations, and authority relied upon for the claim. Nothing in this communication should be treated as an admission of liability.\n\nYours faithfully,\n[Your Name]",
  fingerprint: "a1b2c3d4e5f6g7h8",
  detected_laws: [
    {
      law_name: "Cheque dishonour notice",
      act_name: "The Negotiable Instruments Act, 1881",
      section: "Section 138",
      sections: ["Section 138"],
      severity: "Criminal",
      confidence: "Medium",
      confidence_score: 0.62,
      match_reason: "The notice uses payment recovery and cheque dishonour style language, including a short response window.",
      supporting_lines: [
        "You are hereby called upon to make payment within 15 days.",
        "Failure to comply shall compel my client to initiate proceedings.",
      ],
      official_source_title: "India Code",
      official_source_url: "https://www.indiacode.nic.in/",
    },
  ],
  rights_information: [
    {
      title: "Right to seek full supporting documents",
      detailed_explanation: "Before replying or paying, you can ask for the cheque details, return memo, account statement, and proof of the alleged liability.",
      source: "The Negotiable Instruments Act, 1881",
      article_or_section: "Section 138 context / Article 14 fairness",
      official_text_excerpt: "A recipient should have a fair opportunity to understand and contest the basis of the claim.",
      what_user_can_legally_do: ["Ask for the cheque copy and return memo.", "Dispute the liability if the amount or transaction is incorrect."],
      precautions_to_take: ["Do not admit liability casually.", "Keep written records of every reply and document."],
      when_to_contact_legal_aid_or_authority: "Contact legal aid if a criminal complaint is threatened or if you cannot arrange legal help quickly.",
      official_source_title: "India Code",
      official_source_url: "https://www.indiacode.nic.in/",
    },
  ],
  state_detected: "Maharashtra",
  city_detected: "Mumbai",
  state_options: [],
  source_text: "Sample legal notice text used for dashboard preview.",
  location_resources: [
    {
      state: "Maharashtra",
      city: "Mumbai",
      relevant_authority_name: "NALSA / Tele-Law National Helpline",
      helpline_number: "15100",
      official_website: "https://nalsa.gov.in",
      office_support_category: "National legal aid helpline",
      relevance_reason: "National legal aid and Tele-Law support for notice verification, referrals, and next legal steps.",
      availability_hours: "Check official website",
      official_source_title: "National Legal Services Authority",
      is_fallback: false,
    },
  ],
  legal_aid: {
    recommended: true,
    message: "Use the nearest official legal aid contact below to verify the notice, understand your response window, and get referral support.",
    preferred_language: "en",
    case_type: "Payment / Recovery",
    nalsa_url: "https://nalsa.gov.in",
    centers: [
      {
        name: "NALSA / Tele-Law National Helpline",
        state: "Maharashtra",
        city: "Mumbai",
        contact: "15100",
        address: "Use the official website or helpline to find the correct office for Maharashtra.",
      },
    ],
  },
  support_options: {
    legal_aid_message: "Use the nearest official legal aid contact below to verify the notice, understand your response window, and get referral support.",
    legal_aid_centers: [
      {
        name: "NALSA / Tele-Law National Helpline",
        state: "Maharashtra",
        city: "Mumbai",
        contact: "15100",
        address: "Use the official website or helpline to find the correct office for Maharashtra.",
      },
    ],
    helplines: [
      { title: "NALSA / Tele-Law National Helpline", contact: "15100", description: "National legal aid and Tele-Law support for notice verification, referrals, and next legal steps.", channel: "phone" },
    ],
    whatsapp_enabled: false,
  },
};

export const MOCK_HISTORY: HistoryItem[] = [
  {
    id: "1",
    filename: "legal_notice_march.pdf",
    document_type: "Legal Notice",
    case_type: "Payment / Recovery",
    risk_label: "Suspicious",
    risk_score: 72,
    analyzed_at: "2025-03-20T10:30:00Z",
    fingerprint: "a1b2c3d4",
    summary: "Payment recovery notice with suspicious origin and threatening language.",
  },
];
